# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build JAR and Increment Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Maven 3.9.2
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://archive.apache.org/dist/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz
        tar -xvzf apache-maven-3.9.2-bin.tar.gz
        sudo mv apache-maven-3.9.2 /opt/
        sudo ln -s /opt/apache-maven-3.9.2/bin/mvn /usr/bin/mvn

    - name: Increment version
      id: increment_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        PATCH=$(echo $VERSION | awk -F. '{print $3}')
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION=$(echo $VERSION | awk -F. -v patch=$NEW_PATCH '{print $1"."$2"."patch}')
        echo "New version: $NEW_VERSION"
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
        mvn versions:set -DnewVersion=$NEW_VERSION
        mvn versions:commit

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Upload JAR file
      uses: actions/upload-artifact@v3
      with:
        name: myapp-jar
        path: target/*.jar
